### ISSUE TITLE
bug: insert value size is zero

### ISSUE THREAD

**Issue by xiaguan** [MrCroxx/foyer#338]
Reproduce commands(by fuzz)
```
        Input {
            capacity: 95,
            cache_type: S3Fifo,
            operations: [
                Insert(
                    0,
                    0,
                    0,
                ),
                Insert(
                    33,
                    33,
                    143,
                ),
            ],
        }
```
```
thread '<unnamed>' panicked at /home/susun/foyer/foyer-memory/src/eviction/s3fifo.rs:223:13:
assertion failed: self.is_empty()
```

**Comment by MrCroxx** [comment]
`evict` may return `None` even then cache is not empty.

https://github.com/MrCroxx/foyer/blob/main/foyer-memory/src/eviction/s3fifo.rs#L141-L182

If the small queue eviction will be skipped. 

https://github.com/MrCroxx/foyer/blob/main/foyer-memory/src/eviction/s3fifo.rs#L161

And this line subtracts the wrong charges. 🥹 I'll fix the bugs.

**Comment by MrCroxx** [comment]
> `evict` may return `None` even then cache is not empty.
> 
> https://github.com/MrCroxx/foyer/blob/main/foyer-memory/src/eviction/s3fifo.rs#L141-L182
> 
> If the small queue eviction will be skipped.
> 
> https://github.com/MrCroxx/foyer/blob/main/foyer-memory/src/eviction/s3fifo.rs#L161
> 
> And this line subtracts the wrong charges. 🥹 I'll fix the bugs.

#360
